version: '3.3'

volumes:
  db_valume:
  static:
  media_valume:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - db_valume:/var/lib/postgresql/data/
  backend:
    image: hashut/foodgram_backend:latest
    restart: always
    env_file: .env
    volumes:
      - static:/app/static/
      - media_valume:/app/media/
    depends_on:
      - db

  frontend:
    image: hashut/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media_valume:/media/
    depends_on:
      - frontend
    restart: always
