# Generated by Django 3.2.16 on 2023-08-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230823_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение рецепта', null=True, upload_to='images', verbose_name='Изображение рецепта'),
        ),
    ]
