# Generated by Django 3.2.16 on 2023-08-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='collor',
            field=models.CharField(default=1, help_text='От 1 до 3', max_length=3, unique=True, verbose_name='Цвет тега'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(help_text='Введите единицу измерения', max_length=10, verbose_name='Единица измерения'),
        ),
    ]
