# Generated by Django 3.2.16 on 2023-08-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='collor',
            field=models.CharField(help_text='Введите цвет тега', max_length=10, unique=True, verbose_name='Цвет тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Введите slug значение', unique=True, verbose_name='Slug'),
        ),
    ]
